artifact_uri: /home/ubuntu/hooni/MLflow_tutorial/tracking_server/1/2e2b4f4f806e4e7f9faf04e84a5cfa8f/artifacts
end_time: 1647744591216
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2e2b4f4f806e4e7f9faf04e84a5cfa8f
run_uuid: 2e2b4f4f806e4e7f9faf04e84a5cfa8f
source_name: ''
source_type: 4
source_version: ''
start_time: 1647744574192
status: 3
tags: []
user_id: root
